Simpleinjector reimplementation
reactiveui/splat pull request #631
Opened 2020-11-15 16:29 UTC by jposert

**What kind of change does this PR introduce?**
Bugfix

**What is the current behavior?**
Currently there's no way to use SimpleInjector in projects.

**What is the new behavior?**
SimpleInjector works well with Splat & ReactiveUI initializations.

**What might this PR break?**
Probably nothing.

**Please check if the PR fulfills these requirements**
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

**Other information**:
I've tested the solution with my very small project based on WPF - all works okay. Anyway, I've no clue about performance of the solution (probably most important thing on mobile platforms).

2020-11-15 16:29 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/reactiveui/splat?pullRequest=631) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/splat?pullRequest=631) before we can accept your contribution.<br/><br/>:x: jposert [sign now](https://cla.dotnetfoundation.org/reactiveui/splat?pullRequest=631)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/splat?pullRequest=631) it.</sub>

2020-11-15 22:19 UTC, glennawatson commented
There's some failing unit tests unfortunately. You can click the build action to see the details. 

Thanks for the work so far

2020-11-16 20:50 UTC, jposert commented
I made a little mistake and i pushed  invalid code (sorry). For now, everything should be okay but the build is failing - and I'm not sure why or how to fix it. It's all building on my machine and it passes all the tests successfully.

2020-11-16 21:26 UTC, glennawatson commented
The latest is a build error that is on and off we've seen before with Nerdbank git versioning tool we use. I might make a report to the library author.

2020-11-20 08:42 UTC, dpvreony requested changes
thanks, few threading tweaks and some bits around the read me just to expand\ clarify knowledge

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +        public Dictionary<Type, List<Func<object>>> RegisteredFactories { get; }
Can you take a look at the lock logic in https://github.com/reactiveui/splat/blob/7af765b6ac360c93dc217d6380cc045c23c2401a/src/Splat.Autofac/AutofacDependencyResolver.cs

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +            Func<object> fact = RegisteredFactories[serviceType].LastOrDefault();
Thread safety tweak needed with lock see https://github.com/reactiveui/splat/blob/7af765b6ac360c93dc217d6380cc045c23c2401a/src/Splat.Autofac/AutofacDependencyResolver.cs#L55-L61 for example

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +            return RegisteredFactories[serviceType]
thread safety tweak needed
https://github.com/reactiveui/splat/blob/7af765b6ac360c93dc217d6380cc045c23c2401a/src/Splat.Autofac/AutofacDependencyResolver.cs#L88-L103

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +            return RegisteredFactories.TryGetValue(serviceType, out List<Func<object>> values)
thread safety tweak
https://github.com/reactiveui/splat/blob/7af765b6ac360c93dc217d6380cc045c23c2401a/src/Splat.Autofac/AutofacDependencyResolver.cs#L106-L116

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +            if (!RegisteredFactories.ContainsKey(serviceType))
thread safety tweak needed please :)

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/SimpleInjectorInitializer.cs
> +            if (RegisteredFactories.ContainsKey(serviceType))
thread safety tweak needed please :)

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/README.md
> +// Register ReactiveUI dependencies
are these 2 initialize lines actually needed? Splat and ReactiveUI would do these during normal operation. Is there a nuance we need to document so people are aware?

2020-11-20 08:42 UTC, dpvreony commented on src/Splat.SimpleInjector/README.md
> +container.Options.AllowOverridingRegistrations = true;
i appreciate AllowOverridingRegistrations is "optional", but from what i've read of an issue, this actually makes sense to use in certain scenarios, could we just add a little bit of extra detail to the comment. helps for knowledge retention, dev journey and if we can revisit to overcome the issue in future :)

2020-11-20 08:46 UTC, dpvreony commented
housekeeping comment
closes #597

2020-12-02 22:02 UTC, dpvreony commented
cleaned up. documented weakness in dupe registrations

2020-12-02 22:02 UTC, dpvreony approved these changes

2020-12-02 22:19 UTC, merged